boutproject/boutproject.github.io

- Gemfile
- _config.yml
- devel.markdown
- doc.markdown
- download.markdown
- index.markdown
Also some small changes to get site building on a local machine.
> Add link to forum, clarify BOUT-dev is the place to be

- _data/navigation.yml
> Changed projects to applications

- index.html
Adds red "Fork me on GitHub" banner, and big blue Download hyperlink.  See #10
> Fork me banner

- _applications/07-merging-filaments.md
Includes short description, Youtube video, and link to the repository
> Adding merging filaments application

- _layouts/default.html
can I push these changes directly to master, or open a pr?
> try to support https

- index.html
> Update index.html - Add DCU

- _data/navigation.yml
- _includes/header.html
- _layouts/page.html
- assets/css/styles.scss
- documentation/index.md
- documentation/workshop2018.markdown
> Workshop18

- documentation/workshop2018.markdown
update my talk title, and add KS Kang's full name in the agenda.
> johnomotani update

- documentation/workshop2018.markdown
Also a statement neat the start, pointing to the Zenodo community.
> Adding some links to Zenodo talks to the workshop

- _posts/2018-10-17-v4.2.0_released.md
- _posts/2019-01-23-v4.2.1_released.md
> Add posts for v4.2.0 and v4.2.1 release announcements

- Gemfile
- Gemfile.lock
- _config.yml
Also fix deprecated config option name
> Update config to fix Jekyll vulnerability

- _data/navigation.yml
- _includes/header.html
- documentation/index.md
- documentation/workshop2019.markdown
Initial commit changing all 2018s to 2019s, and removing old information.
> Update website for 2019 Workshop

- documentation/workshop2019.markdown
Added link to the venue, for those looking for information and possibly room bookings.
> Add link for the Cosener's House.

- _data/navigation.yml
- _includes/header.html
- assets/css/materialize.scss
- assets/css/styles.scss
Menus look like this:
This allows us to add more items to the navbar without taking up too much horizontal space
> Add dropdown menus to the navbar

- documentation/workshop2019.markdown
Adding D.Schworer's talk, marking G.Wilkie as remote
> Small addition to agenda

- documentation/workshop2019.markdown
Xueqiao Xu now coming in person to present LLNL work
Nami Li giving remote talk from China
> Add speakers, 9am start on 12th

- documentation/workshop2019.markdown
Public map with venue, brewer's tap, bus stops to Oxford and Didcot
> Add map with bus stops

- publications/index.md
There are certainly many papers missing - is there a better way than to manually add them?
> Add my papers (and preprint)

- publications/index.md
This is a PR to update publications for year 2020. Please add more.
> 2020 Publications list

- publications/index.md
This PR is for 2019 publications which have not yet been added to the list.
Please add more.
> 2019 Publication list

- publications/index.md
Trying to follow references to BOUT++ review papers and STORM papers (L.Easy)
An interesting mix, with people running BOUT++ in the UK, US, Japan, Korea, Thailand, Russia, Norway and India.
> Publications update
